### ISSUE TITLE
cppcheck: post-depinst hook failed with host cppcheck

### ISSUE THREAD

**Issue by lzaoral** [csutils/csmock#117]
1. Prepare a CentOS Stream 8 host.
2. Execute `csmock -t gcc,cppcheck,clang,shellcheck -r fedora-39-aarch64 -o /tmp/tmpodhysnjl/libssh2-1.10.0-7.fc38.tar.xz --use-host-cppcheck --gcc-analyze /tmp/tmpodhysnjl/libssh2-1.10.0-7.fc38.src.rpm'`
3. The scan will fail with the following error:
```console 
>>> 2023-08-27 12:56:07	"tar -cP '/usr/share/csmock/scripts' '/usr/bin/cswrap' '/usr/lib64/cswrap' '/usr/bin/csclng' '/usr/lib64/csclng' '/usr/bin/csclng++' '/usr/bin/cscppc' '/usr/lib64/cscppc' '/usr/share/cscppc' '/usr/bin/cppcheck' '/usr/share/Cppcheck' '/usr/bin/csgcca' '/usr/lib64/csgcca' '/tmp/csmock78iz0380/libssh2-1.10.0-7.fc38.src.rpm' | '/usr/bin/mock' '-r' 'fedora-39-aarch64' '--plugin-option=tmpfs:keep_mounted=True' '--config-opts=print_main_output=True' '--quiet' '--shell' 'tar -xC/'"
tar: Removing leading `/' from member names

scan.ini: analyzer-version-clang = 16.0.6
!!! 2023-08-27 12:56:08	error: post-depinst hook failed

>>> 2023-08-27 12:56:08	"/usr/bin/mock" "-r" "fedora-39-aarch64" "--plugin-option=tmpfs:keep_mounted=True" "--config-opts=print_main_output=True" "--quiet" "--clean"

scan.ini: time-finished = 2023-08-27 12:56:10
scan.ini: exit-code = 127
<<< 2023-08-27 12:56:10	csmock exit code: 127

Wrote: /tmp/tmpodhysnjl/libssh2-1.10.0-7.fc38.tar.xz
```

Note that the scan succeeds if you omit the `--use-host-cppcheck` option.

**Comment by kdudka** [comment]
I guess the cause is that `--use-host-cppcheck` assumes that `cppcheck` installed on the host is linked statically, which is usually not the case on a default Fedora installation.  We should probably improve multiple things:
1. document the assumption
2. make `store_cppcheck_version_hook()` in the `cppcheck` plug-in print an error message on failure
3. `csmock` should tell the user which `post-depinst` hook actually failed
